# Generated by Django 3.2.7 on 2022-08-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.TextField(default='')),
                ('status', models.CharField(default='', max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='admin', max_length=12)),
                ('profile_pic', models.ImageField(default='deafult_profile_pic.jpeg', upload_to='user/profile_image')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_user_blocked', models.BooleanField(default=False)),
                ('otp', models.CharField(default='', max_length=200)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=10)),
                ('uzr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='accounts.user')),
            ],
        ),
    ]
