# Generated by Django 3.2.7 on 2022-08-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.TextField(default='', max_length=60)),
                ('store_address', models.CharField(max_length=60)),
                ('store_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.TextField(default='', max_length=60)),
                ('quantity', models.TextField(default='', max_length=60)),
                ('item_price', models.IntegerField(default=0)),
                ('total_amount', models.TextField(default='', max_length=60)),
                ('order_status', models.CharField(default='', max_length=30)),
                ('address', models.TextField(default='', max_length=100)),
                ('Order_booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Order_booked_by', to='accounts.user')),
                ('stores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='User.store_detail')),
            ],
        ),
    ]
